version: "3.9"

services:
  web:
    build: .
    command: gunicorn trucker_app.wsgi:application --bind 0.0.0.0:8000
    volumes:
      - .:/code
    expose:
      -  8000

  nginx:
    build: nginx
    restart: always
    ports:
       -  443:443
       -  80:80
    depends_on:
       -  web

