version: "3.9"

services:
  mongo:
    image: mongo
    restart: always
  web:
    build: .
    command: gunicorn trucker_app.wsgi:application --bind 0.0.0.0:8000
    volumes:
      - .:/code
    ports:
      - 8000:8000
    depends_on:
      - mongo
